/**
 * Authoritative Error Code Constants for the Invoice System.
 * UI translates these error codes to localized messages.
 */
export const INVOICE_ERROR_CODES = {
  CONFLICT_STALE_VERSION: 'CONFLICT_STALE_VERSION',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  PRINT_SNAPSHOT_INVALID: 'PRINT_SNAPSHOT_INVALID',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  INVALID_INVOICE_DATA: 'INVALID_INVOICE_DATA'
};

export default INVOICE_ERROR_CODES;
